FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y ffmpeg

COPY helper.py .
COPY http_download_worker.py .

CMD ["python", "http_download_worker.py"]