FROM youtube-master-base:latest

WORKDIR /app

# Create necessary directory for audio files
RUN mkdir -p static/audio

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY helper.py .
COPY http_download_worker.py .

CMD ["python", "http_download_worker.py"]