FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y ffmpeg curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# This image can be built manually with:
# docker build -t youtube-master-base:latest -f Dockerfile.base . 